####################################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Clements, CS165
# Author:
#     Nimesh Subedi
# Summary:
#     The following programs reads the details of the customers
#     as well as the products and then calculats the Shipping cost 
#     and the sales tax and then adds its together with the base
#     price and then returns the total price. after all the details
#     are together the program displays the recirpt ot the detail
#     of the product of the customer which depends on the user
#     entered input.
####################################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

